steps:
# Step 1: Checkout with full history (important!)
- checkout: self
  fetchDepth: 0

# Step 2: Configure Git
- script: |
    git config --global user.email "buildagent@azuredevops.com"
    git config --global user.name "Azure DevOps Pipeline"
  displayName: "Configure Git"

# Step 3: Add GitHub remote
- script: |
    git remote add github https://Krisha-cmd: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@github.com/Krisha-cmd/graphi-fe.git
  displayName: "Add GitHub remote"

# Step 4: Push changes
- script: |
    git push github HEAD:main --force
  displayName: "Push changes to GitHub"
