trigger:
- main   # or your default branch in Azure Repos

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Checkout the Azure repo code
- checkout: self

# Step 2: Configure Git
- script: |
    git config --global user.email "buildagent@azuredevops.com"
    git config --global user.name "Azure DevOps Pipeline"
  displayName: "Configure Git"

# Step 3: Add GitHub remote
- script: |
    git remote add github https://$Krisha-cmd:$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@github.com/$(Krisha-cmd)/graphi-fe.git
  displayName: "Add GitHub remote"

# Step 4: Push changes to GitHub
- script: |
    # Push current branch to GitHub (example: main)
    git push github HEAD:main --force

    # (Optional) Push all branches and tags
    # git push github --all --force
    # git push github --tags --force
  displayName: "Push changes to GitHub"
